---
title: "Quantile regression"
author: "Gabrielle Durieu"
date: "2024-03-25"
output:
  pdf_document: default
  html_document: default
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = F, message = F, warning = F}
source(file = "~/work/Stat_app/DATA/exporting_data_from_link.R")
```

```{r echo = F, message = F, warning = F}
#Packages :
install.packages("dplyr")
install.packages("ggplot2")
install.packages("labelled")
install.packages("quantreg") # regression
install.packages("lmtest") # statistic tests
install.packages("stargazer") # tables
library("dplyr")
library("ggplot2")
library("labelled")
library("quantreg")
library("stargazer")
library("magrittr") # for %>%

```

exemple Matthieu

```{r}
stargazer::stargazer(reg, title = "Actual working hours regressed on sex, standard errors account for clustering by countries", column.labels = c("Number of hours actually worked in main job"), covariate.labels = c("Sex (1 for male and 2 for female)", "Constant"), model.names = TRUE, keep.stat="n", omit.stat = c("rsq", "adj.rsq","ser","f"))

```

```{r}

# Fit conditional quantile regression
rq_model <- rq(hwactual ~ sex, data = eulfs_small, tau = 0.8)
residuals <- residuals(rq_model)
summary(rq_model)

# Export des résultats vers LaTeX
latex_table <- stargazer(rq_model, title = "Régression Quantile Conditionnelle", 
                         align = TRUE, type = "latex", header = FALSE)
cat(latex_table, file = "regression_table.tex")

#I took the variable sex as an exemple, just to see
# Values seem all meaningless for tau = 0.9 ...

# Summary of the model with additional information
#summary_conditional <- summary.rq(fit_conditional)

# Print summary including confidence intervals and p-values
#print(summary_conditional, digits = 4) 
# no IC, F stat, R-squared ... don't know yet how to make them appear
```

```{r echo= F}
'
data_filtered <- eulfs_small[!is.na(eulfs_small$hwactual), ]


# Define a sequence of tau values from 0.1 to 0.9
tau_values <- seq(0.1, 0.9, by = 0.1)

# List to store the models
models <- list()

# Loop to fit the models for different quantiles
for (tau in tau_values) {
  model <- rq(hwactual ~ sex, data = data_filtered, tau = tau, method = "fn")
  models[[as.character(tau)]] <- model
}

# Print the results for each quantile
for (tau in tau_values) {
  cat("Tau =", tau, "\n")
  summary(models[[as.character(tau)]])
  cat("\n")
}
'
```


```{r}
# For a single value for tau
tau <- 0.3

# List to store the models
reg_models <- list()

# Loop to fit the models for each year
for (year in c(1998, 2013)) {
  # Filter data for the specific year
  data_year <- subset(eulfs_small, year == year)
  
  # Fit the models
  reg_model <- rq(hwactual ~ sex, data = data_year, tau = tau)
  
  # Store the model in the list
  reg_models[[as.character(year)]] <- reg_model
}

# Print the results for each year
print(reg_models, digits = 4) 

```

