---
title: "Quantile regression"
author: "Gabrielle Durieu"
date: "2024-03-25"
output:
  pdf_document: default
  html_document: default
---


```{r echo = F, message = F, warning = F}
source(file = "~/work/Stat_app/DATA/exporting_data_from_link.R")
```

```{r echo = F, message = F, warning = F}
#Packages :
install.packages("dplyr")
install.packages("ggplot2")
install.packages("labelled")
install.packages("quantreg") # regression
install.packages("lmtest") # statistic tests
install.packages("stargazer") # tables
install.packages("xtable")

library("dplyr")
library("ggplot2")
library("labelled")
library("quantreg")
library("stargazer")
library("xtable")
library("magrittr") # for %>%

```


```{r}
# Definition of quantiles, essential for what follows
quantiles <- seq(0.1, 0.9, by = 0.1)
```


```{r}
#Reg for 2013, one variable
eulfs_small_year <- subset(eulfs_small, refyear == 2013)


# Initialise a list to stock the results
results <- list()

# Loop  on each quantile
for (q in quantiles) {
  # Ajust the quant reg model
  rq_model <- rq(hwactual ~ sex, data = eulfs_small_year, tau = q)
  
  # Stock the results in the list
  results[[as.character(q)]] <- summary(rq_model)
}

# Print the results for each quantile
for (q in quantiles) {
  cat("Quantile:", q, "\n")
  print(results[[as.character(q)]])
}

```


```{r}
# Regressions for 1998, one variable
eulfs_small_year <- subset(eulfs_small, refyear == 1998)

# Initialize a list to store the results
results <- list()

# Loop over each quantile
for (q in quantiles) {
  # Fit the quantile regression model
  rq_model <- rq(hwactual ~ sex, data = eulfs_small_year, tau = q)
  
  # Store the results in the list
  results[[as.character(q)]] <- summary(rq_model)
}

# Convert the results to LaTeX using xtable
table_data <- NULL
for (q in quantiles) {
  table_data <- rbind(table_data, c(q, results[[as.character(q)]]$coef[,1]))
}
colnames(table_data) <- c("Quantile", "Intercept", "sex")

# Convert to xtable object
xtable_data <- xtable(table_data)

# Print the LaTeX code for the table
xtable_data

```



```{r}
# For hatlev, education level, we create 3 binary variable

eulfs_small$high_educ <- ifelse(eulfs_small$hatlev1d==3,1,0)
eulfs_small$medium_educ <- ifelse(eulfs_small$hatlev1d==2,1,0)
eulfs_small$low_educ <- ifelse(eulfs_small$hatlev1d==1,1,0)

```


```{r}
# Regressions for a given year
eulfs_small_year <- subset(eulfs_small, refyear == 2013)

# Initialize a list to store the results
results <- list()

# Loop over each quantile
for (q in quantiles) {
  # Fit the quantile regression model with both sex and age
  rq_model <- rq(hwactual ~ sex + high_educ + low_educ, tau = q, data = eulfs_small_year, model = TRUE)
  
  # Store the results in the list
  results[[as.character(q)]] <- summary(rq_model)
}

# Initialize an empty matrix to store the table data
table_data <- matrix(nrow = length(quantiles), ncol = 5)
colnames(table_data) <- c("Quantile", "Intercept", "Sex", "High education", "Low education")

# Loop over each quantile
for (i in seq_along(quantiles)) {
  q <- quantiles[i]
  coef_values <- results[[as.character(q)]]$coef[, 1]
  
  # Populate the table data with relevant coefficients
  table_data[i, ] <- c(q, coef_values["(Intercept)"], coef_values["sex"], coef_values["high_educ"], coef_values["low_educ"])
}

# Convert to xtable object
xtable_data <- xtable(table_data)

# Print the LaTeX code for the table
print(xtable_data)


rm(xtable_data)
```


```{r}
# Regressions for a given year (sex, age, educ)
eulfs_small_year <- subset(eulfs_small, refyear == 2013)


# Initialize a list to store the results
results <- list()

# Loop over each quantile
for (q in quantiles) {
  # Fit the quantile regression model with both sex and age
  rq_model <- rq(hwactual ~ sex + age + high_educ + low_educ, tau = q, data = eulfs_small_year, model = TRUE)
  
  # Store the results in the list
  results[[as.character(q)]] <- summary(rq_model)
}

# Initialize an empty matrix to store the table data
table_data <- matrix(nrow = length(quantiles), ncol = 6)
colnames(table_data) <- c("Quantile", "Intercept", "Sex", "Age", "High education", "Low education")

# Loop over each quantile
for (i in seq_along(quantiles)) {
  q <- quantiles[i]
  coef_values <- results[[as.character(q)]]$coef[, 1]
  
  # Populate the table data with relevant coefficients
  table_data[i, ] <- c(q, coef_values["(Intercept)"], coef_values["sex"], coef_values["age"], coef_values["high_educ"], coef_values["low_educ"])
}

# Convert to xtable object
xtable_data <- xtable(table_data)

# Print the LaTeX code for the table
print(xtable_data)


rm(xtable_data)
```

```{r}
# Filtrer les données pour inclure les années 2011, 2012 et 2013
eulfs_small_years <- subset(eulfs_small, refyear %in% c(2011, 2012, 2013))

# Initialize une liste pour stocker les résultats
results <- list()

# Loop over each quantile
for (q in quantiles) {
  # Fit the quantile regression model with both sex and age
  rq_model <- rq(hwactual ~ sex + age + high_educ + low_educ, tau = q, data = eulfs_small_years, model = TRUE)
  
  # Store the results in the list
  results[[as.character(q)]] <- summary(rq_model)
}

# Initialize an empty matrix to store the table data
table_data <- matrix(nrow = length(quantiles), ncol = 6)
colnames(table_data) <- c("Quantile", "Intercept", "Sex", "Age", "High education", "Low education")

# Loop over each quantile
for (i in seq_along(quantiles)) {
  q <- quantiles[i]
  coef_values <- results[[as.character(q)]]$coef[, 1]
  
  # Populate the table data with relevant coefficients
  table_data[i, ] <- c(q, coef_values["(Intercept)"], coef_values["sex"], coef_values["age"], coef_values["high_educ"], coef_values["low_educ"])
}

# Convert to xtable object
xtable_data <- xtable(table_data)

# Print the LaTeX code for the table
print(xtable_data)

```



```{r}
# Regressions for a given year (sex, age, educ)
eulfs_small_year_clust <- subset(eulfs_small, refyear %in% c(1998, 1999, 2000))


# Initialize a list to store the results
results <- list()

# Loop over each quantile
# Loop over each quantile
for (q in quantiles) {
  # Fit the quantile regression model with both sex and age
  rq_model <- rq(hwactual ~ sex + age + high_educ + low_educ | refyear, tau = q, data = eulfs_small_years, model = TRUE, method = "br")
  
  # Store the results in the list
  results[[as.character(q)]] <- summary(rq_model)
}


# Initialize an empty matrix to store the table data
table_data <- matrix(nrow = length(quantiles), ncol = 5)
colnames(table_data) <- c("Quantile", "Intercept", "Sex", "High education", "Low education")

# Loop over each quantile
for (i in seq_along(quantiles)) {
  q <- quantiles[i]
  coef_values <- results[[as.character(q)]]$coef[, 1]
  
  # Populate the table data with relevant coefficients
  table_data[i, ] <- c(q, coef_values["(Intercept)"], coef_values["sex"], coef_values["high_educ"], coef_values["low_educ"])
}

# Convert to xtable object
xtable_data <- xtable(table_data)

# Print the LaTeX code for the table
print(xtable_data)


rm(xtable_data)
```


```{r}
rq_model <- rq(hwactual ~ sex + high_educ + medium_educ + low_educ, data = eulfs_small_year, tau = 0.5)

# Vérification de la corrélation entre les variables
cor(eulfs_small_year_clust[, c("sex", "high_educ", "medium_educ", "low_educ", "age")])

```




